import MaleyLean.Papers.PvsNP.ClosureByExhaustionOperatorSupport

open MaleyLean.Papers.PvsNP

#print axioms CnfClosureByExhaustionSourceDocument
#print axioms cnfClosureByExhaustionSourceDocument
#print axioms cnfClosureByExhaustionSourceDocumentPopulatedBool_eq_true
#print axioms CnfClosureByExhaustionOperatorSupport
#print axioms cnfSameScopeOperatorClassification_of_closureSupport
#print axioms cnfSameScopeOperatorClosureLaw_of_closureSupport
#print axioms cnfPositiveEndpoint_of_closureByExhaustionSupport
#print axioms cnfPositiveEndpoint_of_closureByExhaustionSupport_kernelScoped
#print axioms cnfClosureByExhaustionSupportResidualTarget
#print axioms cnfPositiveEndpoint_of_closureByExhaustionSupportResidualTarget
#print axioms cnfPositiveEndpoint_of_closureByExhaustionSupportResidualTarget_kernelScoped
