import MaleyLean.Papers.PvsNP.SATOperatorInstantiationLaw

open MaleyLean.Papers.PvsNP

#print axioms CnfSATOperatorInstantiationLaw
#print axioms cnfClosureByExhaustionSupportResidualTarget_of_satOperatorInstantiationLaw
#print axioms cnfSameScopeOperatorClosureLaw_of_satOperatorInstantiationLaw
#print axioms cnfProfiledClosureLaw_of_satOperatorInstantiationLaw
#print axioms cnfAuthenticClosureLaw_of_satOperatorInstantiationLaw
#print axioms cnfSourceReadoutPackage_of_satOperatorInstantiationLaw
#print axioms cnfSeparatingClassifierIndependent_of_satOperatorInstantiationLaw
#print axioms cnfPositiveEndpoint_of_satOperatorInstantiationLaw
#print axioms cnfPositiveEndpoint_of_satOperatorInstantiationLaw_kernelScoped
#print axioms cnfDirectGateResidualTarget
#print axioms cnfDirectGateResidualSuppliedBySATOperatorInstantiationBool_eq_false
#print axioms cnfSATOperatorInstantiationAnchor
#print axioms cnfSATOperatorInstantiationAnchor_holds
#print axioms CnfSATOperatorInstantiationAudit
#print axioms cnfSATOperatorInstantiationAudit
#print axioms CnfSATOperatorInstantiationAudit.auditComplete_holds
