import MaleyLean.Papers.PvsNP.SATBridgeAuthenticityAudit

open MaleyLean.Papers.PvsNP

#print axioms CnfSATCanonicalPlaceholder
#print axioms cnfSATCanonicalPlaceholders_length_eq
#print axioms CnfSATStrengthenedInterfaceSubgoal
#print axioms cnfSATStrengthenedInterfaceSubgoals_length_eq
#print axioms CnfSATStrengthenedInterfaceSubgoalRow
#print axioms cnfSATStrengthenedInterfaceSubgoalRows_subgoals_match
#print axioms cnfSATStrengthenedInterfaceSubgoalRowsAllSuppliedBool_eq_true
#print axioms cnfSATStrengthenedInterfaceSubgoalRowsOpenCount_eq
#print axioms cnfSATStrengthenedInterfaceSubgoalRowsSuppliedCount_eq
#print axioms cnfSATStrengthenedInterfaceSubgoalRowsLeanTargets_eq
#print axioms CnfSATStrengthenedOperatorInterface
#print axioms cnfSATStrengthenedOperatorInterfaceResidualTarget
#print axioms cnfSATStrengthenedOperatorInterfaceSuppliedByCanonicalBridgeBool
#print axioms cnfSATStrengthenedOperatorInterfaceSuppliedByCanonicalBridgeBool_eq_false
#print axioms cnfSATCanonicalBridgeUsesPlaceholderStandingBool
#print axioms cnfSATCanonicalBridgeUsesPlaceholderStandingBool_eq_true
#print axioms cnfSATBridgeAuthenticityAuditComplete_holds
