import MaleyLean.Papers.PvsNP.SATStrictBridgeAssembly

open MaleyLean.Papers.PvsNP

#print axioms CnfSATStrictBridgeAssemblyInputs
#print axioms cnfSATOperatorStrictBridgePackage_of_assemblyInputs
#print axioms cnfSATStrictBridgeAssemblyInputs_of_supportResidual
#print axioms cnfSATOperatorStrictBridgePackage_of_supportResidual
#print axioms cnfSATStrictBridgeAssemblyInputs_canonical
#print axioms cnfSATOperatorStrictBridgePackage_canonical
#print axioms cnfSATOperatorStrictBridgeResidualTarget_of_assemblyInputs
#print axioms cnfSATOperatorStrictBridgeResidualTarget_of_supportResidual
#print axioms cnfSATOperatorStrictBridgeResidualTarget_canonical
#print axioms cnfSATOperatorInstantiationLaw_nonempty_canonical
#print axioms cnfSATOperatorBridgeCallable_positiveEndpoint_of_assemblyInputs
#print axioms cnfSATOperatorBridgeCallable_positiveEndpoint_of_assemblyInputs_kernelScoped
#print axioms MaleyLean.Papers.PvsNP.cnfSATOperatorBridgeCallable_positiveEndpoint_of_assemblyInputs_nonvacuousKernel
#print axioms cnfSATOperatorBridgeCallable_positiveEndpoint_of_supportResidual
#print axioms cnfSATOperatorBridgeCallable_positiveEndpoint_of_supportResidual_kernelScoped
#print axioms MaleyLean.Papers.PvsNP.cnfSATOperatorBridgeCallable_positiveEndpoint_of_supportResidual_nonvacuousKernel
#print axioms cnfSATOperatorBridgeCallable_positiveEndpoint_canonical
#print axioms cnfSATOperatorBridgeCallable_positiveEndpoint_canonical_kernelScoped
#print axioms MaleyLean.Papers.PvsNP.cnfSATOperatorBridgeCallable_positiveEndpoint_canonical_nonvacuousKernel
#print axioms CnfSATStrictBridgeEndpointInputs
#print axioms CnfSATStrictBridgeEndpointInputsKernelScoped
#print axioms MaleyLean.Papers.PvsNP.CnfSATStrictBridgeEndpointInputsNonvacuousKernel
#print axioms cnfSATStrictBridgeEndpointInputCount
#print axioms cnfSATStrictBridgeEndpointInputCount_eq
#print axioms cnfSATOperatorBridgeCallable_positiveEndpoint_of_endpointInputs
#print axioms cnfSATOperatorBridgeCallable_positiveEndpoint_of_endpointInputs_kernelScoped
#print axioms MaleyLean.Papers.PvsNP.cnfSATOperatorBridgeCallable_positiveEndpoint_of_endpointInputs_nonvacuousKernel
#print axioms cnfDirectGateResidualSuppliedByStrictBridgeAssemblyBool
#print axioms cnfDirectGateResidualSuppliedByStrictBridgeAssemblyBool_eq_false
#print axioms cnfSATStrictBridgeAssemblyAnchor
#print axioms cnfSATStrictBridgeAssemblyAnchor_holds
#print axioms CnfSATStrictBridgeAssemblyCertificate
#print axioms cnfSATStrictBridgeAssemblyCertificate
#print axioms CnfSATStrictBridgeAssemblyCertificate.auditComplete_holds
