import MaleyLean.Papers.PvsNP.CorpusBridgeLedger

open MaleyLean.Papers.PvsNP

#print axioms CnfBridgeSourceDocument
#print axioms cnfBridgeSourceDocument
#print axioms cnfBridgeSourceDocumentPopulatedBool_eq_true
#print axioms CnfBridgeObligation
#print axioms cnfBridgeObligations_length_eq
#print axioms CnfBridgeSourceCrosswalkRow
#print axioms cnfBridgeSourceCrosswalk_length_eq
#print axioms cnfBridgeSourceCrosswalk_obligations_match
#print axioms cnfBridgeSourceCrosswalk_titles_match
#print axioms cnfBridgeSourceCrosswalkLeanAnchors_eq
#print axioms cnfBridgeSourceCrosswalkCoreNoResidualEndpointLeanAnchor
#print axioms cnfBridgeSourceCrosswalkCoreNoResidualEndpointLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkCoreNoResidualImpossibilitySuiteEndpointLeanAnchor
#print axioms cnfBridgeSourceCrosswalkCoreNoResidualImpossibilitySuiteEndpointLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkCoreNoResidualEndpointInputCount_eq
#print axioms cnfBridgeSourceCrosswalkPrimitiveEndpointLeanAnchor
#print axioms cnfBridgeSourceCrosswalkPrimitiveEndpointLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkPrimitiveEndpointCertificateLeanAnchor
#print axioms cnfBridgeSourceCrosswalkPrimitiveEndpointCertificateLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkPrimitiveEndpointInputCount_eq
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedEndpointLeanAnchor
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedEndpointLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedEndpointCertificateLeanAnchor
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedEndpointCertificateLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedBoundaryInterfaceLeanAnchor
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedBoundaryInterfaceLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedEndpointInputCount_eq
#print axioms cnfBridgeSourceCrosswalkPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkCompleteBool_eq_true
#print axioms cnfBridgeSourceCrosswalkAllSuppliedBool_eq_false
#print axioms cnfBridgeSourceCrosswalkAuditComplete_holds
