import MaleyLean.Papers.PvsNP.AnticheckerReduction

open MaleyLean.Papers.PvsNP

#print axioms CnfEncodedCandidateModel
#print axioms CnfEncodedAnticheckerPackage
#print axioms CnfEncodedAnticheckerSelection
#print axioms CnfEncodedAnticheckerFeasibility
#print axioms CnfEncodedAnticheckerSeparation
#print axioms cnfEncodedAnticheckerPackage_of_selectionFeasibilitySeparation
#print axioms CnfEncodedAnticheckerSplitResidual
#print axioms cnfEncodedAnticheckerPackage_of_splitResidual
#print axioms cnfEncodedAnticheckerSplitResidual_of_package
#print axioms cnfEncodedAnticheckerPackage_nonempty_iff_splitResidual
#print axioms cnfEncodedAnticheckerSelection_of_counterexampleLowerBound
#print axioms cnfEncodedAnticheckerFeasibility_of_counterexampleLowerBound
#print axioms cnfEncodedAnticheckerSeparation_of_counterexampleLowerBound
#print axioms cnfEncodedAnticheckerPackage_of_counterexampleLowerBound
#print axioms counterexampleLowerBound_of_encodedAntichecker
#print axioms noCnfMachineTarget_of_encodedAntichecker
#print axioms noCnfSATInPolyTime_of_encodedAntichecker
#print axioms cnfEncodedAnticheckerPackage_nonempty_iff_counterexampleLowerBound
