import MaleyLean.Papers.PvsNP.SATOperatorRealizationProgram

open MaleyLean.Papers.PvsNP

#print axioms CnfSATOperatorRealizationProfile
#print axioms cnfSameScopeClassifierOperator_of_realizationProfile
#print axioms cnfCanonicalSameScopeClassifierOperator
#print axioms cnfSATOperatorRealizationProfile_of_separatingClassifier
#print axioms CnfSATOperatorRealizationLaw
#print axioms cnfSATOperatorRealizationLaw_canonical
#print axioms cnfSeparatingClassifierHasSameScopeOperator_of_realizationLaw
#print axioms cnfSATOperatorInstantiationLaw_of_realizationLaw
#print axioms cnfPositiveEndpoint_of_realizationLaw_and_closureSupport
#print axioms cnfPositiveEndpoint_of_realizationLaw_and_closureSupport_kernelScoped
#print axioms cnfSATOperatorRealizationResidualTarget
#print axioms cnfSeparatingClassifierHasSameScopeOperator_of_realizationResidualTarget
