import MaleyLean.Papers.PvsNP.SATOperatorAuditRunners

open MaleyLean.Papers.PvsNP

#eval cnfSATOperatorFocusedAuditRunnerFiles
#eval cnfSATOperatorAggregateAuditRunnerFiles
#eval cnfSATOperatorAuditRunnerFiles
#eval cnfSATOperatorAuditRunnerFilesDuplicateFreeBool
#eval cnfSATOperatorAuditRunnerFilesPopulatedBool
#eval cnfSATOperatorAuditRunnerFormalizationStatusSummary
#eval cnfSATOperatorAuditRunnerProgressSummary

#print axioms cnfSATOperatorFocusedAuditRunnerFiles_count_eq
#print axioms cnfSATOperatorAggregateAuditRunnerFiles_count_eq
#print axioms cnfSATOperatorAuditRunnerFiles_count_eq
#print axioms cnfSATOperatorAuditRunnerFiles_decomposes
#print axioms cnfSATOperatorFocusedAuditRunnerFilesDuplicateFreeBool_eq_true
#print axioms cnfSATOperatorAggregateAuditRunnerFilesDuplicateFreeBool_eq_true
#print axioms cnfSATOperatorAuditRunnerFilesDuplicateFreeBool_eq_true
#print axioms cnfSATOperatorFocusedAuditRunnerFilesPopulatedBool_eq_true
#print axioms cnfSATOperatorAuditRunnerFilesPopulatedBool_eq_true
#print axioms cnfSATOperatorAuditRunnerFormalizationStatusCovered_holds
#print axioms cnfSATOperatorAuditRunnerRegistryComplete_holds
