import MaleyLean.Papers.PvsNP.SATOperatorProofQueue
import MaleyLean.Papers.PvsNP.SATOperatorStatusLedger
import MaleyLean.Papers.PvsNP.CorpusBridgeCallability

open MaleyLean.Papers.PvsNP

#print axioms CnfSATOperatorSameRegimeInducedOperatorExhaustionAPlusBoundaryDerivedSourceClosure
#print axioms cnfAmetricBivalentBoundaryInterface_nonempty_of_aPlusCertificate
#print axioms cnfSATOperatorProofQueueAmetricBivalentBoundaryInterface_nonempty_of_aPlusCertificate
#print axioms cnfSATOperatorProofQueueSameRegimeInducedOperatorExhaustionAPlusBoundaryDerivedSourceClosure_iff_sources
#print axioms cnfSATOperatorProofQueueSameRegimeInducedOperatorExhaustionPrimitiveSourceClosure_of_aPlusBoundaryDerivedSourceClosure
#print axioms cnfSATOperatorProofQueuePositiveEndpoint_of_sameRegimeInducedOperatorExhaustionAPlusBoundaryDerivedSourceClosure
#print axioms cnfSATOperatorSameRegimeInducedOperatorExhaustionAPlusBoundaryDerivedOpenFactCount_eq
#print axioms CnfSATOperatorSameRegimeInducedOperatorExhaustionAPlusBoundaryDerivedSourceClosureCertificate
#print axioms cnfSATOperatorProofQueueSameRegimeInducedOperatorExhaustionAPlusBoundaryDerivedSourceClosureCertificate
#print axioms CnfSATOperatorSameRegimeInducedOperatorExhaustionAPlusBoundaryDerivedSourceClosureCertificate.boundaryInterface
#print axioms CnfSATOperatorSameRegimeInducedOperatorExhaustionAPlusBoundaryDerivedSourceClosureCertificate.auditComplete
#print axioms CnfSATOperatorSameRegimeInducedOperatorExhaustionAPlusBoundaryDerivedSourceClosureCertificate.auditComplete_holds
#print axioms cnfSATOperatorStatusLedgerPreferredAPlusBoundaryDerivedSourceClosureLeanAnchor_populated
#print axioms cnfSATOperatorStatusLedgerPreferredAPlusBoundaryDerivedSourceClosureInputCount_eq
#print axioms cnfSATOperatorStatusLedgerPreferredAPlusBoundaryDerivedSourceClosureOpenInputCount_eq
#print axioms cnfSATOperatorStatusLedgerPreferredAPlusBoundaryDerivedSourceClosureCallableBool_eq_true
#print axioms cnfSATOperatorStatusLedgerPreferredAPlusBoundaryDerivedSourceClosureSuppliedBool_eq_false
#print axioms cnfSATOperatorStatusLedgerPreferredAPlusBoundaryDerivedSourceClosureCertificateLeanAnchor_populated
#print axioms cnfSATOperatorStatusLedgerPreferredAPlusBoundaryDerivedBoundaryInterfaceLeanAnchor_populated
#print axioms cnfSATOperatorSourceCrosswalkPreferredAPlusBoundaryDerivedLeanAnchorPopulatedBool_eq_true
#print axioms cnfSATOperatorSourceCrosswalkPreferredAPlusBoundaryDerivedCertificateLeanAnchorPopulatedBool_eq_true
#print axioms cnfSATOperatorSourceCrosswalkPreferredAPlusBoundaryDerivedBoundaryInterfaceLeanAnchorPopulatedBool_eq_true
#print axioms cnfSATOperatorSourceCrosswalkPreferredAPlusBoundaryDerivedInputCount_eq
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedEndpointLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedEndpointCertificateLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedBoundaryInterfaceLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgeSourceCrosswalkAPlusBoundaryDerivedEndpointInputCount_eq
#print axioms cnfBridgePreferredAPlusBoundaryDerivedEndpointClosureLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgePreferredAPlusBoundaryDerivedEndpointClosureCertificateLeanAnchorPopulatedBool_eq_true
#print axioms cnfBridgePreferredAPlusBoundaryDerivedBoundaryInterfaceLeanAnchorPopulatedBool_eq_true
