import MaleyLean.Papers.PvsNP.SATClosureSupportInstantiation

open MaleyLean.Papers.PvsNP

#print axioms CnfSATBookkeepingProfile
#print axioms cnfFixedQuotientReadoutProfile_of_bookkeepingProfile
#print axioms CnfSATInadmissibilityProfile
#print axioms cnfImportedOrCentral_of_inadmissibilityProfile
#print axioms cnfCentralBoundaryTraceProfile_of_separatingClassifier
#print axioms cnfSATInadmissibilityProfile_of_centralTrace
#print axioms CnfSATClosureSupportInstantiationLaw
#print axioms cnfSATClosureSupportInstantiationLaw_canonical
#print axioms cnfClosureByExhaustionOperatorSupport_of_satClosureSupportLaw
#print axioms cnfSATOperatorInstantiationLaw_of_realization_and_supportInstantiation
#print axioms cnfPositiveEndpoint_of_realization_and_supportInstantiation
#print axioms cnfPositiveEndpoint_of_realization_and_supportInstantiation_kernelScoped
#print axioms cnfSATClosureSupportInstantiationResidualTarget
#print axioms cnfClosureByExhaustionOperatorSupport_of_supportResidualTarget
