import MaleyLean.Papers.PvsNP.SATStrengthenedInterfaceAssembly

open MaleyLean.Papers.PvsNP

#print axioms CnfSATRealizationStandingSemantics
#print axioms CnfSATCentralTraceStandingSemantics
#print axioms CnfSATInadmissibilityAuxiliarySemantics
#print axioms CnfSATNoTrivialStandingDischarge
#print axioms cnfSATRealizationStandingSemanticsResidualTarget
#print axioms cnfSATCentralTraceStandingSemanticsResidualTarget
#print axioms cnfSATInadmissibilityAuxiliarySemanticsResidualTarget
#print axioms cnfSATNoTrivialStandingDischargeResidualTarget
#print axioms CnfSATStrengthenedInterfaceAssemblyInputs
#print axioms cnfSATStrengthenedOperatorInterface_of_assemblyInputs
#print axioms cnfSATStrengthenedOperatorInterfaceResidualTarget_of_assemblyInputs
#print axioms cnfSATStrengthenedOperatorInterfaceResidualTarget_of_residualTargets
#print axioms cnfSATStrengthenedInterfaceAssemblySuppliedBool
#print axioms cnfSATStrengthenedInterfaceAssemblySuppliedBool_eq_false
#print axioms CnfSATStrengthenedInterfaceAssemblyCertificate
#print axioms cnfSATStrengthenedInterfaceAssemblyCertificate
#print axioms CnfSATStrengthenedInterfaceAssemblyCertificate.auditComplete_holds
